version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: vehiclems
    environment:
      MYSQL_ROOT_PASSWORD: fiap-root
      MYSQL_DATABASE: vehicle-mysql
      MYSQL_USER: dev
      MYSQL_PASSWORD: fiap
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: